using UmaMusumeAPI.Controllers;

namespace UmaMusumeAPI.Models.Tables
{
    [GeneratedController]
    public class RaceBgmPattern
    {
        public int Id { get; set; }
        public int BgmTime1 { get; set; }
        public string BgmCueName1 { get; set; }
        public string BgmCuesheetName1 { get; set; }
        public int BgmTime2 { get; set; }
        public string BgmCueName2 { get; set; }
        public string BgmCuesheetName2 { get; set; }
        public int BgmTime3 { get; set; }
        public string BgmCueName3 { get; set; }
        public string BgmCuesheetName3 { get; set; }
        public int BgmTime4 { get; set; }
        public string BgmCueName4 { get; set; }
        public string BgmCuesheetName4 { get; set; }
        public int BgmTime5 { get; set; }
        public string BgmCueName5 { get; set; }
        public string BgmCuesheetName5 { get; set; }
        public int BgmTime6 { get; set; }
        public string BgmCueName6 { get; set; }
        public string BgmCuesheetName6 { get; set; }
        public int BgmTime7 { get; set; }
        public string BgmCueName7 { get; set; }
        public string BgmCuesheetName7 { get; set; }
        public int BgmTime8 { get; set; }
        public string BgmCueName8 { get; set; }
        public string BgmCuesheetName8 { get; set; }
        public int BgmTime9 { get; set; }
        public string BgmCueName9 { get; set; }
        public string BgmCuesheetName9 { get; set; }
        public int BgmTime10 { get; set; }
        public string BgmCueName10 { get; set; }
        public string BgmCuesheetName10 { get; set; }
        public int BgmTime11 { get; set; }
        public string BgmCueName11 { get; set; }
        public string BgmCuesheetName11 { get; set; }
        public int BgmTime12 { get; set; }
        public string BgmCueName12 { get; set; }
        public string BgmCuesheetName12 { get; set; }
        public int BgmTime13 { get; set; }
        public string BgmCueName13 { get; set; }
        public string BgmCuesheetName13 { get; set; }
        public int BgmTime14 { get; set; }
        public string BgmCueName14 { get; set; }
        public string BgmCuesheetName14 { get; set; }
        public int BgmTime15 { get; set; }
        public string BgmCueName15 { get; set; }
        public string BgmCuesheetName15 { get; set; }
        public int BgmTime16 { get; set; }
        public string BgmCueName16 { get; set; }
        public string BgmCuesheetName16 { get; set; }
        public int BgmTime17 { get; set; }
        public string BgmCueName17 { get; set; }
        public string BgmCuesheetName17 { get; set; }
        public int BgmTime18 { get; set; }
        public string BgmCueName18 { get; set; }
        public string BgmCuesheetName18 { get; set; }
        public int BgmTime19 { get; set; }
        public string BgmCueName19 { get; set; }
        public string BgmCuesheetName19 { get; set; }
        public int BgmTime20 { get; set; }
        public string BgmCueName20 { get; set; }
        public string BgmCuesheetName20 { get; set; }
        public int BgmTime21 { get; set; }
        public string BgmCueName21 { get; set; }
        public string BgmCuesheetName21 { get; set; }
        public int BgmTime22 { get; set; }
        public string BgmCueName22 { get; set; }
        public string BgmCuesheetName22 { get; set; }
        public int BgmTime23 { get; set; }
        public string BgmCueName23 { get; set; }
        public string BgmCuesheetName23 { get; set; }
        public int BgmTime24 { get; set; }
        public string BgmCueName24 { get; set; }
        public string BgmCuesheetName24 { get; set; }
        public int BgmTime25 { get; set; }
        public string BgmCueName25 { get; set; }
        public string BgmCuesheetName25 { get; set; }
        public int BgmTime26 { get; set; }
        public string BgmCueName26 { get; set; }
        public string BgmCuesheetName26 { get; set; }
        public int BgmTime27 { get; set; }
        public string BgmCueName27 { get; set; }
        public string BgmCuesheetName27 { get; set; }
        public int BgmTime28 { get; set; }
        public string BgmCueName28 { get; set; }
        public string BgmCuesheetName28 { get; set; }
        public int BgmTime29 { get; set; }
        public string BgmCueName29 { get; set; }
        public string BgmCuesheetName29 { get; set; }
        public int BgmTime30 { get; set; }
        public string BgmCueName30 { get; set; }
        public string BgmCuesheetName30 { get; set; }
    }
}
